### PR TITLE
Added an introductory video to the page

### PR DESCRIPTION
**Pull request by mkannisto**
## Proposed changes

I added the embedded introductory video to the new SD Connect.

Link to the preview page: https://csc-guide-preview.rahtiapp.fi/origin/SD-Connect-Beta-video/data/sensitive-data/sd-connect-beta/

## Checklist before requesting a review

- [X] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [X] My pull request passes all tests.
- [X] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

### CODE REVIEW

**Comment by joonas-somero** [comment]
Yes, the "incorrect" attribute name _src_ was introduced when the url was fixed. If it seems ridiculous to go through all of this just to add a simple video, it's because it absolutely is! The current mechanism is a relic from earlier and I'm working on a fix.

**Comment by joonas-somero** [comment]
There we go! Now if we could just get someone to sign off on this... :grin:

**Review by fmorelloCSC — APPROVED** [review]

**Comment by fmorelloCSC** [comment]
Sorry I received several notifications so lost track of it, now approved

**Comment by joonas-somero** [comment]
> Sorry I received several notifications so lost track of it, now approved

Oh no I didn't mean to criticize. I just start to make jokes like that when I'm in a good mood. :slightly_smiling_face: Have a nice weekend!

**Pull request merged**
