### PR TITLE
HTC update

### PR DESCRIPTION
**Pull request by ktiits**
https://csc-guide-preview.rahtiapp.fi/origin/ktiits-workflows/computing/running/throughput/

### CODE REVIEW

**Comment by ktiits** [comment]
Added links to NextFlow and Snakemake apps pages, the tutorial links added to these pages.
+
Changes as agreed in meeting with Laxman, Sami and Antoni.

Graph:
Remove: Serial or parallel subtasks? 
Move Array and GNU Parallel under No answer of dependecies
Kylli

A qualitative overview of the features and capabilities of some of the workflow tools recommended by CSC is presented below. -> HTC tools

Table:
Packs jobs/job steps
Snakemak Yes
GNU Parallel NA
Array job No

Dependency support
Array jobs No

Container support -> Automatic container integration
The workflow tool supports execution with containers -> The workflow tool supports automatic execution of containers without any extra work.
Array jobs - No
GNU Parallel - No

error recovery
snakemake - Yes

Parallelization support	-> MPI/OpenMP-parallel subtasks
The workflow tool supports MPI/OpenMP-parallel subtasks

New row: multi-partition support
Support 
NextFlow, Snakemake: pay attention
Array jobs, GNU: no
Fireworks, HyperQueue: ??

**Comment by ktiits** [comment]
@samiilvonen promised to see also the srun note, because that is rather unclear text now.

**Comment by attesillanpaa** [comment]
Hi! This looks great! Please also consider, once ready, adding a whatsnew entry and the link also in the tutorials section!

**Comment by ktiits** [comment]
In tutorials, there already is/was a link. 
But with whatsnew I am not familiar, how to add stuff there. Could somebody else do that? Or I do not know if it is even worth adding there, the changes here are still rather small scale?

**Comment by attesillanpaa** [comment]
It's is worth adding what's new. It's super easy. See instructions here: https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#how-do-i-add-an-entry-to-the-whats-new-section

When it's here, it gets shown on the landing page *and* mentioned in the next newsletter.

**Comment by ktiits** [comment]
Laxmana is doing updates also to Snakemake page in another PR. I would suggest that we do one common What's new for both of these PRs.

**Comment by yetulaxman** [comment]
Thanks, Kylli. Flowchart and table look bit more clear now.  Could we add a sentence or two to describe flowchart? And also links provided in the flowchart are broken with an exception to snakemake. Currently, snakemake URL points to external documentation while others to our CSC docs. Not sure if these broken links will be resolved in production.

**Review by yetulaxman — APPROVED** [review]

**Pull request merged**
