### PR TITLE
WIP: Fix allas urls

### PR DESCRIPTION
**Pull request by galfthan**
Replaced object.pouta.csc.fi => a3s.fi

### CODE REVIEW

**Comment by galfthan** [comment]
@Kallio pointed out that all commands need to be tested to make sure they work with  a3s too

**Comment by Nortamo** [comment]
#188 fixes the links, other changes are incorporated in this pull request.

**Comment by Nortamo** [comment]
Don't work on this, I will fix some things using reset and force push!

**Comment by Nortamo** [comment]
The links were fixed in #188 and no additional changes are done here, so  I will close this.

**Pull request closed without merging**
