### PR TITLE
Connecting with SSH keys, reorganizing + RStudio/Jupyter Notebook tutorial

### PR DESCRIPTION
**Pull request by ktiits**

### CODE REVIEW

**Comment by jussienko** [comment]
Lots of good stuff, however, I feel that the tunneling related stuff is here out of context (i.e. note that powershell does not support jump hosts and instructions for setting tunneling for Putty). I would suggest to discuss tunneling settings in the context of relevant application (i.e. RStudio or Jupyter), or if it feels that there are generic enough use cases we should have a separate "ssh tunneling artcile".

**Review by jussienko — COMMENTED** [review]
Excellet work!

Tiny comments: 

"Manual copying keys" part has in the text Windows syntax for path (`\`) but Linux one (`/`) in the example command.

Link to tutorial is missing from the main tutorial page (support/tutorials/).

Maybe the link to tutorial could be included in the first section of "interactive-usage", and the two examples later on completely removed.

**Comment by ktiits** [comment]
> "Manual copying keys" part has in the text Windows syntax for path (\) but Linux one (/) in the example command.
Only the Windows example left with \, others changed to /.

> Link to tutorial is missing from the main tutorial page (support/tutorials/).
Added.

Maybe the link to tutorial could be included in the first section of "interactive-usage", and the two examples later on completely removed.
> Link added and 2 examples removed.

**Review by jussienko — APPROVED** [review]
Mycket bra!

**Pull request merged**
