### PR TITLE
Buttons for simple feedback on specific page

### PR DESCRIPTION
**Pull request by joonas-somero**
https://csc-guide-preview.rahtiapp.fi/origin/feedback-buttons/

image

After clicking on "Yes":
image

After clicking on "No":
image

Prefilled title and label in new issue:
Feedback

### CODE REVIEW

**Comment by rkronberg** [comment]
Text suggestions:
* **Yes**:  
Thank you for you feedback!
* **No**:  
Thank you for your feedback! Please let us know how we could improve this page by [contacting us](https://docs.csc.fi/support/contact/) or by [creating an issue in GitHub](https://github.com/CSCfi/csc-user-guide/issues/new). You can also [edit this page yourself](https://github.com/CSCfi/csc-user-guide/edit/master/docs/index.md) and contribute your improvements through a pull request.

The link to editing would of course be different for each page (same as when clicking the pen icon at the top of a page).

**Comment by rkronberg** [comment]
Maybe also the 'Do you find this page useful?' could be written in past tense 'Did you find this page useful?' I guess you need to first read the page in order to then decide whether it was useful or not?

**Comment by joonas-somero** [comment]
> Maybe also the 'Do you find this page useful?' could be written in past tense 'Did you find this page useful?' I guess you need to first read the page in order to then decide whether it was useful or not?

I'm viewing the site as a handbook where pages are constantly revisited, so the idea here is that the page presently exists and is either useful or not.

**Comment by rkronberg** [comment]
> > Maybe also the 'Do you find this page useful?' could be written in past tense 'Did you find this page useful?' I guess you need to first read the page in order to then decide whether it was useful or not?
> 
> I'm viewing the site as a handbook where pages are constantly revisited, so the idea here is that the page presently exists and is either useful or not.

Fair enough, that makes also sense!

**Comment by joonas-somero** [comment]
> > > Maybe also the 'Do you find this page useful?' could be written in past tense 'Did you find this page useful?' I guess you need to first read the page in order to then decide whether it was useful or not?
> > 
> > 
> > I'm viewing the site as a handbook where pages are constantly revisited, so the idea here is that the page presently exists and is either useful or not.
> 
> Fair enough, that makes also sense!

Oh, and when the page source file changes, the previous selection is removed and the buttons shown again. That makes it an on-going dialog, rather than a one time "yes" or "no".

**Comment by rkronberg** [comment]
Preview of this branch seems to not be building correctly. Other branches are fine, so I wonder if this is an issue with the changes made here and whether those could also be carried over to production?

**Comment by joonas-somero** [comment]
> Preview of this branch seems to not be building correctly. Other branches are fine, so I wonder if this is an issue with the changes made here and whether those could also be carried over to production?

Looks fine now. :man_shrugging: Perhaps preview fixed itself over the weekend.

**Review by jemaltahir — COMMENTED** [review]
Look at the minor suggestion, if you consider there are benefits you can change it. Otherwise it's LGTM (JS) files.

**Review by jemaltahir — COMMENTED** [review]
Changes have been applied.

**Pull request merged**
