### PR TITLE
Update Gromacs 2022.4

### PR DESCRIPTION
**Pull request by rkronberg**
https://csc-guide-preview.rahtiapp.fi/origin/gromacs-2022.4/support/wn/apps-new/#gromacs-20224-1612023

### CODE REVIEW

**Comment by rkronberg** [comment]
Split also some lines and fixed typos in `apps-new.md` for better readability.

**Comment by joonas-somero** [comment]
> Split also some lines and fixed typos in `apps-new.md` for better readability.

Wouldn't editing such news feed type of content after almost a year and a half after its original release be, in a way, a bit dubious?

**Comment by rkronberg** [comment]
> > Split also some lines and fixed typos in `apps-new.md` for better readability.
> 
> Wouldn't editing such news feed type of content after almost a year and a half after its original release be, in a way, a bit dubious?

Fair point. Since the content was not modified in any way, I think it should be ok?

**Comment by joonas-somero** [comment]
> > > Split also some lines and fixed typos in `apps-new.md` for better readability.
> > 
> > 
> > Wouldn't editing such news feed type of content after almost a year and a half after its original release be, in a way, a bit dubious?
> 
> Fair point. Although since the actual content was not modified in any way (just typos and formatting of the source), I think it should be ok?

I can live with that. :slightly_smiling_face:

**Review by joonas-somero — APPROVED** [review]

**Pull request merged**
