### PR TITLE
LUMI-Helmi Docs

### PR DESCRIPTION
**Pull request by JMuff22**
lumi-helmi branch contains lots of changing to add documentation for Quantum Computing, in particular for the 5 qubit quantum computer Helmi as well as for the upcoming Pilot Phase. This PR should not be merged until the start of the LUMI-Helmi pilot phase. ~The estimated date for this is 23.09~. **Do not merge until then**.

Additions:

- New "Quantum Computing" top level entry has been added. Most of the additions are here.
- Kvasi QLM documentation has moved from computing/ --> quantum-computing
- Documentation for Helmi is under quantum-computing and this includes
- first-quantum-job.md (How to run your first job on Helmi)
- helmi_accounts.md (Project and accounting information)
- helmi_quick.md (A quick start guide for LUMI-Helmi)
- lumi-helmi-pilot-phase.md (pilot phase specific information)
- running-on-helmi.md (How to run jobs on Helmi)

General changes to docs.csc.fi:

Helmi user guide is added to the front page under "Quick links"

Two new additions to the glossary:
- PI: Principle Investigator
- PM: Project Manager

`tests/check_partitions.sh` for the Github repo has `q_fiqci` added. 

Link to Rahti preview: https://csc-guide-preview.rahtiapp.fi/origin/lumi-helmi/

Style and Language suggestions are appreciated to make this merge more in the style of the rest of docs!

### CODE REVIEW

**Comment by joonas-somero** [comment]
Should the Quantum Computing section be moved under Computing? Another option would be to break it down and sprinkle the bits (or _qubits_ ...anyone? no?) to Systems etc., but I think it is special and different enough to have it's own section under Computing.

**Comment by rkronberg** [comment]
I second Joonas' idea. Having "Quantum Computing" and "Computing" as separate menus is a bit like having "Tutorials" and "Chemistry Tutorials", right?

**Comment by mpjohans** [comment]
> I second Joonas' idea. Having "Quantum Computing" and "Computing" as separate menus is a bit like having "Tutorials" and "Chemistry Tutorials", right?

Chemistry tutorials are of course the most important of tutorials :-)  But no, we can move "Quantum Computing" one level in, under "Computing", otherwise keeping the structure.

It should not be kept as its own section, and not sprinkled here and there.

**Comment by JMuff22** [comment]
- Added link to examples
- Removed mentioning "From here fill in the applied **resources**: 1440 QPUm from `helmi_accounts.md` as I considered this pilot phase specific information. 
- For pilot phase specific information I added detailed instructions for filling in the New Project form on my.csc.fi: 4(thousand) CPU core hours (24hrs is 3.072 but increased to 4), 0 GPU hours (obviously), 1.2 (thousand) TiB storage hours. The storage billing is slightly confusing but 1.2 thousand is enough for 50 TB for 24 hours so should be plenty.

**Comment by JMuff22** [comment]
Should a copy of the Helmi terms of use be attached to the docs as well as mentioning it?

**Comment by JMuff22** [comment]
Ready for review.

**Pull request merged**
