### PR TITLE
Applications by license

### PR DESCRIPTION
**Pull request by joonas-somero**
https://csc-guide-preview.rahtiapp.fi/origin/license-tags/apps/by_license/

image

### CODE REVIEW

**Comment by Nortamo** [comment]
Should we link/add some information on what exactly the different types mean or is this directly apparent to the user?

**Comment by joonas-somero** [comment]
> Should we link/add some information on what exactly the different types mean or is this directly apparent to the user?

Another option would be to have the tags be just a bit longer. Like 'Free for academic use'.

**Comment by rkronberg** [comment]
Perhaps there could be a short description under each tag on the index page? And clicking the tags on the application page would link to the corresponding anchor on the index page with the explanation?

**Comment by joonas-somero** [comment]
> This looks very nice! Would it make sense to add a what's-new item e.g. in the applications category: (something along the lines) new view to available software: grouped by license type.

That _would_ make sense, yes. I'll just add that before merging.

**Comment by rkronberg** [comment]
Looks good! I guess this can be merged?

**Pull request merged**
