### PR TITLE
New font as per the CSC Design System

### PR DESCRIPTION
**Pull request by joonas-somero**
https://csc-guide-preview.rahtiapp.fi/origin/museo-font/

### CODE REVIEW

**Comment by joonas-somero** [comment]
Font weight seems a bit heavy.

**Comment by joonas-somero** [comment]
That's better.

**Comment by joonas-somero** [comment]
Now boldfaced text inside a paragraph is too light.

**Comment by joonas-somero** [comment]
Much better.

**Review by rkronberg — APPROVED** [review]
ok

**Pull request merged**
