### PR TITLE
Adding Best Practices for Client Side Encryption

### PR DESCRIPTION
**Pull request by mlehtiva**
Moving this page from research.csc.fi: https://research.csc.fi/best-practices-for-client-side-encryption
 Making it visible as a link under Working with data contents page: https://docs.csc.fi/data/datasets/dataset-sources/, but not showing it in navigation, in order to not mess the navigation (it would go under Tips page, but that is already very long).

### CODE REVIEW

**Comment by mlehtiva** [comment]
Preview of the page: https://csc-guide-preview.rahtiapp.fi/origin/mlehtiva-encryption-best-practices/data/datasets/best-encryption-practices/
Preview of the content page: https://csc-guide-preview.rahtiapp.fi/origin/mlehtiva-encryption-best-practices/data/datasets/dataset-sources/

**Comment by mlehtiva** [comment]
Tua: me and Monica added this page here. It is invisible in the navigation, but linked under "Tips for data management". Does that seem ok?
Kimmo: This page had a timestamp 2019, after which SD services etc are published. Could you take a look and update if needed?

**Comment by mlehtiva** [comment]
KimmoM: "Tämä sivu sopii siirtää docksiin, senisitive data osion alle, missä se pitäisi vielä uudelleenkirjoittaa vastaamaan nykyistä tilannetta. Minun varmaan pitäisi tehdä se. Juttelen asiasta Francescan kanssa."

**Comment by mlehtiva** [comment]
Sorry Monika, KimmoMs comment above says: "This page can be moved to docs, under sensitive data section, where it should be written to (better) reflect the current situation. I [Kimmo] should probably do that. I'll talk to Francesca about this."  That's the current status.

**Comment by joonas-somero** [comment]
The commit history of my latest push isn't at all what I intended, though I think the end result is. So, don't worry if the history looks a bit, well, like what it looks like now. :grimacing:

**Review by kkmattil — APPROVED** [review]

**Pull request merged**
