### PR TITLE
Rahti migrate

### PR DESCRIPTION
**Pull request by juhanikataja**
This contains documentation from rahti.csc.fi in almost verbatim.
Only major content change was that contact for support was changed to servicedesk@cscfi from rahti-support@csc.fi.
I have a feeling that some of the content should not be in docs.csc.fi (e.g. agreements or getting access?) but here they are for the lack of more suitable place.
Preview [here](https://csc-guide-preview.rahtiapp.fi/origin/rahti-migrate/).

### CODE REVIEW

**Comment by Nortamo** [comment]
The following links are not working properly

```
Link #information-security--data-protection in file ./docs/cloud/rahti/agreements/sla.md on line 153 is broken
Link /cloud/rahti/usage/projects_and_quota/#projects_and_quota in file ./docs/cloud/rahti/tutorials/basic-console.md on line 6 is broken
Link /cloud/rahti/usage/projects_and_quota/#projects_and_quota in file ./docs/cloud/rahti/tutorials/elemental_tutorial.md on line 96 is broken
Link /cloud/rahti/tutorials/elemental_tutorial#routes in file ./docs/cloud/rahti/usage/security-guide.md on line 24 is broken
```
links 2-4 lead to a **404** page. The sections referenced to don't seem to exist in the files
link 1 just takes you to the top of the page, the section seems to be incorrectly typed. 


There are two files which are not referenced to:

```
./docs/cloud/rahti/agreements/README.md
./docs/cloud/rahti/introduction/service_description.md
```
Are the they needed in the master branch or could they be left out?

**Comment by Nortamo** [comment]
Links check for relative links without .md extension is not working properly, so some of the test report a false positive.

**Comment by Nortamo** [comment]
Fix now in #149, should work. I will check this again tomorrow morning.

**Comment by juhanikataja** [comment]
The work on rahti-user-guide side is here: https://github.com/CSCfi/rahti-user-guide/pull/28

**Comment by djixyacine** [comment]
Looks good to me.

**Pull request merged**
