### PR TITLE
changed license renewal

### PR DESCRIPTION
**Pull request by attesillanpaa**
https://csc-guide-preview.rahtiapp.fi/origin/ms-license-change/apps/materialsstudio/

### CODE REVIEW

**Comment by mmatthiesencsc** [comment]
Looks good!

**Review by mmatthiesencsc — CHANGES_REQUESTED** [review]
Do we use British English?

**Comment by attesillanpaa** [comment]
we need to discuss this later

**Review by mmatthiesencsc — APPROVED** [review]
Now all good!

**Pull request merged**
