### PR TITLE
Change CSC Notebooks to Noppe

### PR DESCRIPTION
**Pull request by rkronberg**
## Proposed changes

Combines multiple PRs by @katrite

https://csc-guide-preview.2.rahtiapp.fi/origin/noppe/

## Checklist before requesting a review

- [x] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [x] My pull request passes the automated tests. If not, visit [pull requests at Travis CI](https://app.travis-ci.com/github/CSCfi/csc-user-guide/pull_requests) and have a look at the job log.
- [x] I have included a link to the appropriate [preview page](https://csc-guide-preview.2.rahtiapp.fi/origin/) (select your branch from the list).

### CODE REVIEW

**Comment by rkronberg** [comment]
@katrite since the `csc_notebooks` directory has been renamed as `noppe`, some incoming (and internal) links will break. Fixing the internal links is easy, but what to do with incoming links (e.g. from research.csc.fi?). I would at least suggest setting up a redirect `cloud/csc_notebooks` -> `cloud/noppe`

**Comment by rkronberg** [comment]
@katrite @helhotti @tourunen just to clarify, are the renaming changes here pending for some changes elsewhere? Or would you have time to approve the PR so we get the changes into production? :)

**Comment by tourunen** [comment]
This is waiting for the actual change. We are currently doing the migration in our QA and soon in production as well.

**Review by tourunen — APPROVED** [review]
Tweaked cloud news and Noppe main page, good to go now IMO. Big thanks for your effort Rasmus! Since noppe.csc.fi is already online and the redirect links work, this can be merged.

**Pull request merged**
