### PR TITLE
Added/updated OOD usage to GIS modules with GUI

### PR DESCRIPTION
**Pull request by samumantha**
WIP because of NoMachine way.

Should all NoMachine instructions be removed from these pages, @ktiits ?

For SAGA and GRASS GIS the Nomachine instructions are combined with interactive usage. Should the interactive usage part be kept or completely removed?

### CODE REVIEW

**Comment by ktiits** [comment]
> WIP because of NoMachine way.
> 
> Should all NoMachine instructions be removed from these pages, @ktiits ?
> 
> For SAGA and GRASS GIS the Nomachine instructions are combined with interactive usage. Should the interactive usage part be kept or completely removed?

I would remove everything related to NoMachine, but leave the commands visible that are required for launching the GUI from terminal.

For Saga, GRASS and SNAP, I would say that OOD is recommended way for GUI, but option 1 for computing would still be CLI. 

Its likely time to remove the older saga-gis documentation from docs.

**Comment by samumantha** [comment]
Should the whole old saga-gis module be removed, or only usage instructions?

**Comment by samumantha** [comment]
SAGA and GRASS have only instructions for interactive use, should this be rephrased, to include also usage from batch scripts?

**Comment by ktiits** [comment]
> SAGA and GRASS have only instructions for interactive use, should this be rephrased, to include also usage from batch scripts?

Yes. GRASS has examples in Github. For SAGA Rsagacmd could be recommended for scripting.

**Review by ktiits — APPROVED** [review]

**Pull request merged**
