### PR TITLE
Sensitive data faqfix

### PR DESCRIPTION
**Pull request by fmorelloCSC**
faq fix

### CODE REVIEW

**Review by lkalliok — APPROVED** [review]

**Comment by attesillanpaa** [comment]
There are failing tests. Please check why (see the contribute guide for help), commit the fixes and when the tests pass, check also the actual content that it's ok, then accept.

**Comment by rkronberg** [comment]
These FAQ entries may also be helpful: https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#my-pr-did-not-pass-the-tests-what-to-do and https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#i-was-asked-to-review-a-pr-what-should-i-do

**Comment by fmorelloCSC** [comment]
> These FAQ entries may also be helpful: https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#my-pr-did-not-pass-the-tests-what-to-do and https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#i-was-asked-to-review-a-pr-what-should-i-do

**Comment by fmorelloCSC** [comment]
> > These FAQ entries may also be helpful: https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#my-pr-did-not-pass-the-tests-what-to-do and https://github.com/CSCfi/csc-user-guide/blob/master/FAQ.md#i-was-asked-to-review-a-pr-what-should-i-do

sorry. Was trying to answer.... I changed a spelling mistake in a paragraph title and did not remember to change the link to it, so the link got broken. I still need to make few more changes now to instructions we installed yesterday on a new feature in SD Desktop and will try again tomorrow.

**Pull request closed without merging**
