### PR TITLE
Add documentation on how to send emails in Rahti. 

### PR DESCRIPTION
**Pull request by lvarin**
This is just to add documentation on how to send emails in Rahti.

This documentation is taken from Pouta's docs. It is copied over to Rahti's to give visibility to Rahti users.

### CODE REVIEW

**Review by tfrisk — APPROVED** [review]

**Comment by lvarin** [comment]
I will add an example, so the headers to use are more clear.

**Comment by lvarin** [comment]
Ready to review

**Comment by joasilva** [comment]
Looks good python-wise and can actually be quite useful of our users :-)

**Review by joasilva — APPROVED** [review]
Looks good python-wise and can actually be quite useful of our users :-)

**Pull request merged**
