### PR TITLE
Sensitive data faqfix

### PR DESCRIPTION
**Pull request by fmorelloCSC**

### CODE REVIEW

**Comment by fmorelloCSC** [comment]
I fixed the FAQ in the support folder (there was a spelling mistake in one link) and the SD Desktop guide (data export paragraph). However, I am not able to fix the what's new part. I created a new paragraph called data management, but now the .md file is not liked anywhere and Travis is complaining. The news does not have to be in that file, I can delete it. I am just not sure where I should add those updates.

**Comment by rkronberg** [comment]
I renamed and whitelisted the new what's new file. But there's still a few links that seem to be broken. Could you double check these?

**Comment by fmorelloCSC** [comment]
Hi again and sorry about this. I tried to fix this link to days now, but it keeps on giving me an error. It is in the FAQ index.

The section link sensitive-data-encryption.md#do-sensitive-data-always-need-to-be-encrypted-during-upload-or-data-transfer-eg-using-an--ssh-connection in file docs/support/faq/index.md on line 107 is broken

Not sure what to do, but I could just remove that question :-)

**Comment by rkronberg** [comment]
There was one extra dash: ... `an--ssh-connection` ... -> ... `an-ssh-connection` ...
Removed it for you :)

**Review by kkmattil — APPROVED** [review]

**Pull request merged**
