### PR TITLE
How can I change billing project (replaced)

### PR DESCRIPTION
**Pull request by penikune**

### CODE REVIEW

**Comment by penikune** [comment]
See here:
https://github.com/CSCfi/csc-user-guide/issues/134

**Comment by penikune** [comment]
I requested two reviews, so please do not merge immediately after your review.

**Comment by Nortamo** [comment]
#530 is in conflict with #540. Doing some more heavy handed modifications

**Comment by Nortamo** [comment]
Merge will be done through #555

**Pull request closed without merging**
