### PR TITLE
make some links more accessible

### PR DESCRIPTION
**Pull request by attesillanpaa**
formulate as link, add a screen reader friendly text

https://csc-guide-preview.rahtiapp.fi/origin/tykky-links/computing/containers/tykky/

### CODE REVIEW

**Comment by rkronberg** [comment]
Should Tykky have an entry under "Apps"? And perhaps add to what's new?

**Comment by attesillanpaa** [comment]
What's new: absolutely! I guess Apps entry would be ok, too.

**Review by rkronberg — APPROVED** [review]
Ok. Leaving out the apps entry for now, would require moving tykky.md under apps or then editing the scripts.

**Comment by attesillanpaa** [comment]
Maybe we can (later) make a stub entry in apps, and point here from there?

**Pull request merged**
