### PR TITLE
OOD docs updates and restructuring

### PR DESCRIPTION
**Pull request by rkronberg**
## Proposed changes

Updates to Web Interface documentation. Restructure and clarify index page. Improve Allas usage documentation.

https://csc-guide-preview.rahtiapp.fi/origin/ood-docs-update/

## Checklist before requesting a review

- [x] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [x] My pull request passes all tests.
- [x] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

### CODE REVIEW

**Comment by rkronberg** [comment]
I think this PR is ready for review. We did not edit the individual apps-pages yet, let's do improvements there in a separate PR (e.g. improve Jupyter instructions).

**Comment by robinkar** [comment]
It might be good to have some additional instructions for when the interactive apps fail to launch. Right now we mention "launch the app again", but it might be good to have some instructions beyond that, maybe on the "Interactive Apps" page. Common failures could be Lustre issues, job ran out of memory, invalid form options (invalid Python installation for Jupyter), etc.

**Comment by rkronberg** [comment]
Good point. I'll add a subsection "Troubleshooting" on the "Interactive Apps" page.

**Review by robinkar — APPROVED** [review]
Looks good.

**Pull request merged**
